### ISSUE TITLE
INFOGRAFIA 

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/infografia-carlos-chrs-1#1]
[Título.pdf](https://github.com/SistemasTecTlaxiaco/infografia-carlos-chrs-1/files/8054923/Titulo.pdf)
![Título](https://user-images.githubusercontent.com/79929498/153738023-309e399c-47cb-4d3a-9e1f-8974f3f9b112.png)

**Comment by Brisa-4** [comment]
[1. RUBRICA_PARA_EVALUAR_UNA_INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-carlos-chrs-1/files/8129605/1.RUBRICA_PARA_EVALUAR_UNA_INFOGRAFIA.pdf)

Porcentaje: 20%

**Comment by josealfredo79** [comment]
y el standar???

**Comment by josealfredo79** [comment]
Bien hecho y revisado
